version: '3.4'

services:

  weatherclient:
    build: ./weatherclient
    ports:
     - "8085:8085"
    tty:
      true
    restart:
      unless-stopped

  nginx:
    image: nginx:alpine
    ports:
     - "88"
    restart:
      always
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro

  traefik:
    image: traefik
    command: --web --docker --docker.domain=server.test --logLevel=INFO
    ports:
      - "80:80"
      - "8080:8080"
    # trying to imitate a machine, where Traefik + weatherbackend + Nginx are running all on one machine with DNS active
    # therefore trying to configure Docker DNS alias for weatherbackend to Traefik container, which should route it to
    # weatherbackend
    networks:
      default:
        aliases:
          - weatherbackend.server.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always

  weatherbackend:
    build: ./weatherbackend
    labels:
     - "traefik.backend=weatherbackend"
     - "traefik.frontend.rule=Host:weatherbackend.server.test"
    ports:
     - "8095"
    tty:
      true
    restart:
      unless-stopped

